server:
  port: 8099
  servlet:
    context-path: /

# 域名
domain: yqn.hfzfc.cc

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: blogs
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  #redis
  redis:
    database: 9
    port: 6379
    password: 123456
  #rabbitmq
  rabbitmq:
    host: ${domain}
    port: 35672
    username: root
    password: root
    virtual-host: /
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      #手动ack
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual

#redis自定义配置
redis:
  database: 'blogs'
  key:
    user: 'user'
    admin: 'admin'
    token: 'token'
  expire:
    common: 86400 # 24小时

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#log
logging:
  config: classpath:logback-spring-prod.xml

#file
file:
  # 上传路径
  targetUrl: /upload/blogs/img/
  # 文件最大: 10M
  maxSize: 10485760
  # 返回前缀
  prefix: http://${domain}/img/



# 微信
wechat:
  # 公众号id
  app-id: appid
  # 密钥
  app-secret: appsecret


# 微信支付
wechat-pay:
  # ip
  ip: 127.0.0.1
  # 公众号id
  app-id: appid
  # 商户号
  mch-id: mchid
  # 支付密钥
  pay-secret: paysecret
  # 支付密码
  pay-password: paypassword
  # 支付方式
  trade-type: JSAPI
  # 证书绝对路径
  key-store: weixin/apiclient_cert.p12
  # 支付回调地址
  notify-url: http://${domain}/xxx/v1/front/pay/notify
  # 退款回调地址
  refund-notify-url: http://${domain}/xxx/v1/front/pay/refundNotify
